import React from "react";
import type { Metadata } from "next";
import { Sora, Wix_Madefor_Text, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./layout/header";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const wixMadeforText = Wix_Madefor_Text({
  variable: "--font-wix-madefor-text",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${wixMadeforText.variable} ${openSans.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="grow">
          {children}
        </main>

      </body>
    </html>
  );
}
